from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_list_templates():
    response = client.get("/templates")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert any("id" in template for template in data)


def test_generate_layout_success():
    payload = {
        "elements": [
            {"type": "title", "content": "Test Document"},
            {"type": "subtitle", "content": "Test Subtitle"},
            {"type": "paragraph", "content": "This is a test paragraph."},
            {"type": "list", "list_items": ["Item 1", "Item 2"]},
            {"type": "footer", "content": "Generated by LAYAI"},
        ],
        "template_id": "classic_centered",
    }

    response = client.post("/generate-layout", json=payload)
    assert response.status_code == 200
    assert "<html" in response.text
    assert "Test Document" in response.text


def test_generate_layout_invalid_template():
    payload = {"elements": [], "template_id": "nonexistent_template"}

    response = client.post("/generate-layout", json=payload)
    assert response.status_code == 400
    assert "not registered" in response.json()["detail"]
